main: at.srsyntax.rtp.RTPPlugin
name: SyntaxRTP
version: ${version}

softdepend:
  - Vault

author: SrSyntaxAT
website: https://srsyntax.at/

commands:
  rtp:
    description: Teleport you randomly to a location
    aliases:
      - srtp
      - syntaxrtp